// ══════════════════════════════════════════════════════════════════
// BASE DE DATOS DE LOGROS
// ══════════════════════════════════════════════════════════════════
export const ALL_LOGROS = [
        // ── Exploración ──
        {
          id: "logro_primera_entrada",
          icon: "🏆",
          name: "PRIMER PASO",
          desc: "Llegar al Hall del Museo por primera vez",
          pts: 10,
        },
        {
          id: "logro_eupb_mixes",
          icon: "🎵",
          name: "EUPB MIXES",
          desc: "Descubrir la playlist EUPB desde el logo",
          pts: 5,
        },
        {
          id: "logro_sala_2010",
          icon: "🏛️",
          name: "SALA 2010",
          desc: "Primera visita a la sala 2010",
          pts: 10,
        },
        {
          id: "logro_sala_2011",
          icon: "🏛️",
          name: "SALA 2011",
          desc: "Primera visita a la sala 2011",
          pts: 10,
        },
        {
          id: "logro_sala_2012",
          icon: "🏛️",
          name: "SALA 2012",
          desc: "Primera visita a la sala 2012",
          pts: 10,
        },
        {
          id: "logro_sala_2013",
          icon: "🏛️",
          name: "SALA 2013",
          desc: "Primera visita a la sala 2013",
          pts: 10,
        },
        {
          id: "logro_sala_2014",
          icon: "🏛️",
          name: "SALA 2014",
          desc: "Primera visita a la sala 2014",
          pts: 10,
        },
        {
          id: "logro_sala_2015",
          icon: "🏛️",
          name: "SALA 2015",
          desc: "Primera visita a la sala 2015",
          pts: 10,
        },
        {
          id: "logro_sala_2016",
          icon: "🏛️",
          name: "SALA 2016",
          desc: "Primera visita a la sala 2016",
          pts: 10,
        },
        {
          id: "logro_sala_2017",
          icon: "🏛️",
          name: "SALA 2017",
          desc: "Primera visita a la sala 2017",
          pts: 10,
        },
        {
          id: "logro_sala_2018",
          icon: "🏛️",
          name: "SALA 2018",
          desc: "Primera visita a la sala 2018",
          pts: 10,
        },
        {
          id: "logro_sala_2019",
          icon: "🏛️",
          name: "SALA 2019",
          desc: "Primera visita a la sala 2019",
          pts: 10,
        },
        // ── Hitos de misiones ──
        {
          id: "logro_dj_museo",
          icon: "🎧",
          name: "DJ DEL MUSEO",
          desc: "Completar la misión del jukebox",
          pts: 10,
        },
        {
          id: "logro_critico_novato",
          icon: "✍️",
          name: "CRÍTICO NOVATO",
          desc: "Votar y comentar por primera vez",
          pts: 10,
        },
        {
          id: "logro_explorador_completo",
          icon: "🗺️",
          name: "EXPLORADOR COMPLETO",
          desc: "Votar 3+ discos en cada una de las 10 salas",
          pts: 30,
        },
        {
          id: "logro_artista_urbano",
          icon: "🎨",
          name: "ARTISTA URBANO",
          desc: "Pintar tu primer graffiti",
          pts: 15,
        },
        {
          id: "logro_critico_musical",
          icon: "🎤",
          name: "CRÍTICO MUSICAL",
          desc: "Comentar en 5 discos diferentes",
          pts: 20,
        },
        {
          id: "logro_cartero_rap",
          icon: "📮",
          name: "CARTERO DEL RAP",
          desc: "Dejar una sugerencia en las 10 salas",
          pts: 25,
        },
        {
          id: "logro_coleccionista",
          icon: "🏛️",
          name: "COLECCIONISTA",
          desc: "Visitar las 10 salas del museo",
          pts: 30,
        },
        {
          id: "logro_museo_completado",
          icon: "👑",
          name: "MUSEO COMPLETADO",
          desc: "Completar todas las misiones del museo",
          pts: 50,
        },
      ];
